from psutil import cpu_freq
MUTATION_RATE = 0.3
ELITE_RATE = 0.1
TRUNCATION_RATE = 0.5

MIN_PARENT_AGE = 2
MAX_RANDOM_AGE = 10
OLD_AGE = 10

PCT_OF_PARENT = 0.3
TOURNAMENT_PARTICIPANTS = 0.05

EXP_COEFFICIENT = 10
INERTIA_MIN = 0.4
INERTIA_MAX = 0.9
C1 = 2
C2 = 2
CLOCK_RATE = cpu_freq().current * (2 ** 20)
