from psutil import cpu_freq

STUCK_PCT = 0.25

MUTATION_RATE = 0.7
ELITE_RATE = 0.1
TRUNCATION_RATE = 0.5

MIN_PARENT_AGE = 2
MAX_RANDOM_AGE = 10
OLD_AGE = 10

PCT_OF_PARENT = 0.3
TOURNAMENT_PARTICIPANTS = 0.05

EXP_COEFFICIENT = 5
INERTIA_MIN = 0.4
INERTIA_MAX = 0.9
C1 = 2
C2 = 2
CLOCK_RATE = cpu_freq().current * (2 ** 20)

COORDINATES = 0
DEMAND = 1

ANNEALING_ALPHA = 0.98
# for Tabu Search
INITIAL_TABU_TENURE = 10
# Simulated Annealing Parameters
SA_TEMPERATURE = 2000
# ACO parameters
# parameters explained in lab report
ACO_ALPHA = 2
ACO_BETA = 5
ACO_SIGMA = 3
ACO_RO = 0.8
ACO_TAU = 80